# global variables #
title: "Longvity® Center Berlin"

# jekyll configuration #
permalink: pretty

# translation variables #
translations:
    en:
        navigation: "Navigation"
        resources: "Resources"
        home: "Home"
        priorities: "Priorities"
        contact: "Contact"
        imprint: "Imprint"
        privacy: "Privacy"
    de:
        navigation: "Navigation"
        resources: "Ressourcen"
        home: "Home"
        priorities: "Schwerpunkte"
        contact: "Kontakt"
        imprint: "Impressum"
        privacy: "Datenschutz"
