<footer class="navbar navbar-static-bottom">
  <div class="col-md-8 col-md-offset-2">
  {% if language == 'de' %}
  <ul class="col-md-3 list-unstyled">
    <li class="title">Navigation</li>
    <li><a href="#main">Startseite</a></li>
    <li><a href="#sections">Schwerpunkte</a></li>
    <li><a href="#contact">Kontakt</a></li>
  </ul>
  <ul class="col-md-3 list-unstyled">
    <li class="title">Resourcen</li>
    <li><a href="/de/legal#imprint">Impressum</a></li>
    <li><a href="/de/legal#privacy">Datenschutz</a></li>
  </ul>
  <ul class="col-md-3 list-unstyled">
    <li class="title">Partner</li>
    <li><a href="#">Longvity® Center</a></li>
    <li><a href="#">Longvity® Beauty</a></li>
  </ul>
  <ul class="col-md-3 list-unstyled">
    <li class="title">Social</li>
    <li><a href="#">Folgt...</a></li>
  </ul>
  {% else %}
  <ul class="col-md-3 list-unstyled">
    <li class="title">Navigation</li>
    <li><a href="#main">Home</a></li>
    <li><a href="#sections">Priorities</a></li>
    <li><a href="#contact">Contact</a></li>
  </ul>
  <ul class="col-md-3 list-unstyled">
    <li class="title">Resources</li>
    <li><a href="/en/legal#imprint">Imprint</a></li>
    <li><a href="/en/legal#privacy">Privacy Policy</a></li>
  </ul> 
  <ul class="col-md-3 list-unstyled">
    <li class="title">Partner</li>
    <li><a href="#">Longvity® Center</a></li>
    <li><a href="#">Longvity® Beauty</a></li>
  </ul>
  <ul class="col-md-3 list-unstyled">
    <li class="title">Social</li>
    <li><a href="#">Comming soon...</a></li>
  </ul>
  {% endif %}
  </div>
</footer>
